# Generated by Django 6.0.7 on 2026-07-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0003_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='transaction_type',
            field=models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent')], default='sale', max_length=10, verbose_name='Transaction Type'),
        ),
    ]
